name: Docker Base Image CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  docker-base-ci: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Test Server Docker image Builds
      run: docker build -f Dockerfile.base .