name: Docker Image CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker-ci-cd: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push Base Node Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.base
        push: true
        tags: codexrems/node14-pkg-config:latest
      
    - name: Build and push Server Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: codexrems/pharmacy-information-system:latest